/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestApplications;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author aleksejtitorenko
 */
public class enterFrame extends javax.swing.JFrame {
    
    FileReader file;
    JSONParser parser = new JSONParser();
    JSONObject usr;
    JSONArray questionsArray;
    /**
     * Creates new form enterFrame
     * @throws java.io.FileNotFoundException
     */
    public enterFrame(JSONObject usr) throws FileNotFoundException, Exception {
        this.usr = usr;
        file = new FileReader("tests/test1.json");
        questionsArray = (JSONArray) parser.parse(file);
        this.file.close();
        initComponents();
        this.FIOLabel.setText(usr.get("name").toString() +" "
                + usr.get("lastName").toString()+" "
                + usr.get("firstName").toString());
        for (int i = 0; i < questionsArray.size(); i++) {
            JSONObject tmp = (JSONObject) questionsArray.get(i);
            this.testsComboBox.addItem(tmp.get("name"));
        }
    }

    private enterFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FIOLabel = new javax.swing.JLabel();
        testsComboBox = new javax.swing.JComboBox();
        startTestButton = new javax.swing.JButton();
        buttonResults = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        FIOLabel.setText("ФИО");

        testsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                testsComboBoxItemStateChanged(evt);
            }
        });

        startTestButton.setText("Пройти тест");
        startTestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startTestButtonMousePressed(evt);
            }
        });
        startTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTestButtonActionPerformed(evt);
            }
        });

        buttonResults.setText("Отправить результаты");
        buttonResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FIOLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(testsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonResults)
                            .addComponent(startTestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FIOLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startTestButton))
                .addGap(18, 18, 18)
                .addComponent(buttonResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTestButtonActionPerformed
        int i = this.testsComboBox.getSelectedIndex();
        JSONObject temp = (JSONObject) questionsArray.get(i);
        Long j = (Long) temp.get("type");
        if (j==1){
        try {
            new frameTest1((JSONObject) questionsArray.get(i), usr).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(enterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (j==2){
        try {
            new frameTest2((JSONObject) questionsArray.get(i), usr).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(enterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }            
        }
        if (j == 3) {
            try {
                new Test3View((JSONObject) questionsArray.get(i), usr).setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(enterFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (j == 4) {
            try {
                new Test4View((JSONObject) questionsArray.get(i), usr).setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(enterFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_startTestButtonActionPerformed

    private void startTestButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startTestButtonMousePressed
        
    }//GEN-LAST:event_startTestButtonMousePressed

    private boolean isTestComplited(JSONArray o, Number s) {
        int i = s.intValue();
        return o.get(i).equals(0);
    }
    
    private void testsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_testsComboBoxItemStateChanged
        JSONArray i = (JSONArray) usr.get("testsArray");
        Long j = (Long)i.get(this.testsComboBox.getSelectedIndex());
        if (j == 1) {
            this.startTestButton.setEnabled(false);
            this.startTestButton.setText("Вы уже прошли этот тест");
            
        } else {
            this.startTestButton.setEnabled(true);
            this.startTestButton.setText("Пройти тест");
        }
    }//GEN-LAST:event_testsComboBoxItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened
    private void updateSendButton() {
        JSONArray sendedResults = (JSONArray) usr.get("sendedResults");
        JSONArray complitedTests = (JSONArray) usr.get("testsArray");
        if (sendedResults.equals(complitedTests)) {
            buttonResults.setEnabled(false);
            buttonResults.setText("<html>Вы не прошли новых <p>тестов</html>");
        } else {
            buttonResults.setEnabled(true);
            buttonResults.setText("<html>Отправить результаты</html>");
        }
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        JSONArray i = (JSONArray) usr.get("testsArray");
        Long j = (Long) i.get(this.testsComboBox.getSelectedIndex());
        if (j == 1) {
            this.startTestButton.setEnabled(false);
            this.startTestButton.setName("Пройти тест");
            
        } else {
            this.startTestButton.setEnabled(true);
            this.startTestButton.setName("Вы уже прошли этот тест");
        }
        updateSendButton();
    }//GEN-LAST:event_formWindowActivated

    private void buttonResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResultsActionPerformed
        JSONArray complitedTests = (JSONArray) usr.get("testsArray");
        
        try {
            CSVWorker.makeCSVTemplate(((Long)usr.get("ID")).intValue());
        } catch (Exception ex) {
            Logger.getLogger(enterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        usr.put("sendedResults", complitedTests);
        try {
            FileReader file = new FileReader("users/users.json");
            JSONParser parser = new JSONParser();
            JSONArray x = (JSONArray) parser.parse(file);
            file.close();
            int l = ((Long)usr.get("ID")).intValue();
            x.set(l, usr);
            FileWriter fileW = new FileWriter("users/users.json");
            fileW.append(x.toString());
            fileW.flush();
            updateSendButton();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(enterFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(enterFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(enterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_buttonResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FIOLabel;
    private javax.swing.JButton buttonResults;
    private javax.swing.JButton startTestButton;
    private javax.swing.JComboBox testsComboBox;
    // End of variables declaration//GEN-END:variables
}
