/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestApplications.Views;

import TestApplications.Controllers.SingUpController;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author artemsamsonov
 */
public class SingUpView extends javax.swing.JFrame {
    private SingUpController controller;
    /**
     * Creates new form mainFrame
     */
    public SingUpView() throws Exception {
        this.controller = new SingUpController(this);
        initComponents();
        this.applyButton.addActionListener(this.controller);
        this.textUserType.addKeyListener(this.controller);
        this.textUserLastname.addInputMethodListener(this.controller);
        this.textUserName.addInputMethodListener(this.controller);
        this.textUserSurname.addInputMethodListener(this.controller);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUserLastname = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        labelUserSurname = new javax.swing.JLabel();
        labelUserType = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textUserType = new javax.swing.JTextArea();
        applyButton = new javax.swing.JButton();
        textUserLastname = new javax.swing.JTextField();
        textUserName = new javax.swing.JTextField();
        textUserSurname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Новый пользователь");
        setResizable(false);

        labelUserLastname.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUserLastname.setText("Фамилия: ");
        labelUserLastname.setAutoscrolls(true);

        labelUserName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUserName.setText("Имя: ");
        labelUserName.setAutoscrolls(true);

        labelUserSurname.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUserSurname.setText("Отчество: ");
        labelUserSurname.setAutoscrolls(true);

        labelUserType.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUserType.setText("Должность: ");
        labelUserType.setAutoscrolls(true);

        jScrollPane1.setAutoscrolls(true);

        textUserType.setColumns(15);
        textUserType.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textUserType.setRows(4);
        textUserType.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(textUserType);

        applyButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        applyButton.setText("Создать пользователя");
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                applyButtonMousePressed(evt);
            }
        });
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUserLastname)
                            .addComponent(labelUserSurname)
                            .addComponent(labelUserName))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textUserLastname)
                            .addComponent(textUserName)
                            .addComponent(textUserSurname)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUserType)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserLastname)
                    .addComponent(textUserLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserName)
                    .addComponent(textUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserSurname)
                    .addComponent(textUserSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(labelUserType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        
    }//GEN-LAST:event_applyButtonActionPerformed
    
    private void applyButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMousePressed
        
    }//GEN-LAST:event_applyButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SingUpView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SingUpView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUserLastname;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel labelUserSurname;
    private javax.swing.JLabel labelUserType;
    public javax.swing.JTextField textUserLastname;
    public javax.swing.JTextField textUserName;
    public javax.swing.JTextField textUserSurname;
    public javax.swing.JTextArea textUserType;
    // End of variables declaration//GEN-END:variables
}
