/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestApplications.Views;

import TestApplications.CharsField;
import TestApplications.Controllers.SingUpController;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

/**
 *
 * @author artemsamsonov
 */
public class SingUpView extends javax.swing.JFrame {
    
    private SingUpController controller;
    
    public CharsField textUserLastname = new CharsField(25);
    public CharsField textUserName = new CharsField(20);
    public CharsField textUserSurname = new CharsField(20);
    
    /**
     * Creates new form mainFrame
     * @throws java.lang.Exception
     */
    public SingUpView() throws Exception {
        this.controller = new SingUpController(this);
        
        initComponents();
        
        textUserLastname.setBorder(BorderFactory.createLineBorder(Color.gray));
        textUserName.setBorder(BorderFactory.createLineBorder(Color.gray));
        textUserSurname.setBorder(BorderFactory.createLineBorder(Color.gray));
        
        getContentPane().add(textUserLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 10, 168, -1));
        getContentPane().add(textUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 44, 168, -1));
        getContentPane().add(textUserSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 78, 168, -1));
        pack();
        
        this.textUserLastname.addInputMethodListener(this.controller);
        this.textUserName.addInputMethodListener(this.controller);
        this.textUserSurname.addInputMethodListener(this.controller);
        
        this.applyButton.addActionListener(this.controller);
        this.textUserType.addKeyListener(this.controller);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUserLastname = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        labelUserSurname = new javax.swing.JLabel();
        labelUserType = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textUserType = new javax.swing.JTextArea();
        applyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Новый пользователь");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUserLastname.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUserLastname.setText("Фамилия: ");
        labelUserLastname.setAutoscrolls(true);
        getContentPane().add(labelUserLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        labelUserName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUserName.setText("Имя: ");
        labelUserName.setAutoscrolls(true);
        getContentPane().add(labelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, -1, -1));

        labelUserSurname.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUserSurname.setText("Отчество: ");
        labelUserSurname.setAutoscrolls(true);
        getContentPane().add(labelUserSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, -1, -1));

        labelUserType.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUserType.setText("Должность: ");
        labelUserType.setAutoscrolls(true);
        getContentPane().add(labelUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, -1, -1));

        jScrollPane1.setAutoscrolls(true);

        textUserType.setColumns(15);
        textUserType.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textUserType.setRows(4);
        textUserType.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(textUserType);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 130, 271, -1));

        applyButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        applyButton.setText("Создать пользователя");
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                applyButtonMousePressed(evt);
            }
        });
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(applyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, 271, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        
    }//GEN-LAST:event_applyButtonActionPerformed
    
    private void applyButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMousePressed
        
    }//GEN-LAST:event_applyButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SingUpView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SingUpView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUserLastname;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel labelUserSurname;
    private javax.swing.JLabel labelUserType;
    public javax.swing.JTextArea textUserType;
    // End of variables declaration//GEN-END:variables
}
