/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// TODO сделать результаты теста csv строкой с названиями критериев
package TestApplications.Views;

/**
 *
 * @author artemsamsonov
 */
public class Test1View extends javax.swing.JFrame {
    
    /**
     * Creates new form Test1View
     */

    public Test1View() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        labelQuestion = new javax.swing.JLabel();
        labelAns1 = new javax.swing.JLabel();
        labelAns2 = new javax.swing.JLabel();
        labelAns3 = new javax.swing.JLabel();
        labelAns4 = new javax.swing.JLabel();
        buttonNext = new javax.swing.JButton();
        buttonPrev = new javax.swing.JButton();
        text1 = new javax.swing.JSpinner();
        text2 = new javax.swing.JSpinner();
        text3 = new javax.swing.JSpinner();
        text4 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(470, 410));
        setMinimumSize(new java.awt.Dimension(470, 410));
        setPreferredSize(new java.awt.Dimension(470, 410));
        setResizable(false);

        labelQuestion.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelQuestion.setText("Вопрос");
        labelQuestion.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.disabledText")));
        labelQuestion.setMaximumSize(new java.awt.Dimension(460, 65));
        labelQuestion.setMinimumSize(new java.awt.Dimension(460, 65));
        labelQuestion.setPreferredSize(new java.awt.Dimension(460, 65));

        labelAns1.setText("Ответ 1: ");
        labelAns1.setMaximumSize(new java.awt.Dimension(400, 60));
        labelAns1.setMinimumSize(new java.awt.Dimension(400, 60));
        labelAns1.setPreferredSize(new java.awt.Dimension(400, 60));

        labelAns2.setText("Ответ 2: ");
        labelAns2.setMaximumSize(new java.awt.Dimension(400, 60));
        labelAns2.setMinimumSize(new java.awt.Dimension(400, 60));
        labelAns2.setPreferredSize(new java.awt.Dimension(400, 60));

        labelAns3.setText("Ответ 3: ");
        labelAns3.setMaximumSize(new java.awt.Dimension(400, 60));
        labelAns3.setMinimumSize(new java.awt.Dimension(400, 60));
        labelAns3.setPreferredSize(new java.awt.Dimension(400, 60));

        labelAns4.setText("Ответ 4: ");
        labelAns4.setMaximumSize(new java.awt.Dimension(400, 60));
        labelAns4.setMinimumSize(new java.awt.Dimension(400, 60));
        labelAns4.setPreferredSize(new java.awt.Dimension(400, 60));

        buttonNext.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        buttonNext.setText("Next >");
        buttonNext.setToolTipText("");
        buttonNext.setMaximumSize(new java.awt.Dimension(220, 40));
        buttonNext.setMinimumSize(new java.awt.Dimension(220, 40));
        buttonNext.setPreferredSize(new java.awt.Dimension(220, 40));
        buttonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonNextMousePressed(evt);
            }
        });
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        buttonPrev.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        buttonPrev.setText("< Prev");
        buttonPrev.setMaximumSize(new java.awt.Dimension(220, 40));
        buttonPrev.setMinimumSize(new java.awt.Dimension(220, 40));
        buttonPrev.setPreferredSize(new java.awt.Dimension(220, 40));
        buttonPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPrevMousePressed(evt);
            }
        });
        buttonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrevActionPerformed(evt);
            }
        });

        text1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        text1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 11, 1));
        text1.setMinimumSize(new java.awt.Dimension(50, 30));
        text1.setPreferredSize(new java.awt.Dimension(50, 30));

        text2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        text2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 11, 1));
        text2.setMinimumSize(new java.awt.Dimension(50, 30));
        text2.setPreferredSize(new java.awt.Dimension(50, 30));

        text3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        text3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 11, 1));
        text3.setMinimumSize(new java.awt.Dimension(50, 30));
        text3.setPreferredSize(new java.awt.Dimension(50, 30));

        text4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        text4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 11, 1));
        text4.setMinimumSize(new java.awt.Dimension(50, 30));
        text4.setPreferredSize(new java.awt.Dimension(50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAns4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAns1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAns2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAns3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelAns1, labelAns2, labelAns3, labelAns4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAns1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAns2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAns3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAns4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelAns1, labelAns2, labelAns3, labelAns4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        {
        }    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextMousePressed

    }//GEN-LAST:event_buttonNextMousePressed

    private void buttonPrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPrevMousePressed


    }//GEN-LAST:event_buttonPrevMousePressed

    private void buttonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevActionPerformed
        
    }//GEN-LAST:event_buttonPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test1View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test1View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test1View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test1View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new Test1View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonNext;
    public javax.swing.JButton buttonPrev;
    private javax.swing.JSpinner jSpinner1;
    public javax.swing.JLabel labelAns1;
    public javax.swing.JLabel labelAns2;
    public javax.swing.JLabel labelAns3;
    public javax.swing.JLabel labelAns4;
    public javax.swing.JLabel labelQuestion;
    public javax.swing.JSpinner text1;
    public javax.swing.JSpinner text2;
    public javax.swing.JSpinner text3;
    public javax.swing.JSpinner text4;
    // End of variables declaration//GEN-END:variables
}
